### ISSUE TITLE
Rename base branch to ‘main’

### ISSUE THREAD

**Issue by robpomeroy** [robpomeroy/BrightOS#13]
This shows how long this project has been around… Base branch needs to change to ‘main’.

**Comment by robpomeroy** [comment]
Branch renamed. @DasFaultier Could you please run:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

And close this issue when done? Thanks!

**Comment by DasFaultier** [comment]
Done.
